#!/bin/bash
set -eux

# /!\ Run while in U-Boot

DEBUG_GDB=.debug-grub.gdb
uboot=$(find output/build/uboot-* -type f -name u-boot)
grub=$(find output/build/grub2-* -type f -name kernel.exec)

cat <<END >"$DEBUG_GDB"
target remote :1234
printf "in EL%d\\n", (\$cpsr >> 2) & 3
symbol-file $uboot
set \$gd = (gd_t *)\$x18
printf "U-Boot gd->relocaddr: %x\\n", \$gd->relocaddr
symbol-file
add-symbol-file $uboot \$gd->relocaddr
break efi_load_pe
printf "Boot to continue...\n"
cont

where
finish
printf "GRUB image_base: %x\n", info->image_base
break efi_start_image
cont

where
set \$image_obj = (struct efi_loaded_image_obj *)image_handle
printf "GRUB image_obj->entry: %x\n", \$image_obj->entry
add-symbol-file $grub \$image_obj->entry
break *\$image_obj->entry
cont

where
#cont
END

nl "$DEBUG_GDB"

./output/host/bin/aarch64-linux-gdb \
        -x output/staging/usr/share/buildroot/gdbinit \
        -x "$DEBUG_GDB"
