#!/bin/sh
set -eux

xterm -e \
	output/host/usr/bin/qemu-system-x86_64 \
		-append 'console=ttyS0 earlyprintk' \
		-cpu host \
		-enable-kvm \
		-initrd output/images/rootfs.cpio \
		-kernel output/images/bzImage \
		-m 256 \
		-nographic \
		-s -S \
	&

output/host/usr/bin/x86_64-linux-gdb \
	-x run.gdb \
	output/build/linux-4.2/vmlinux
