#!/bin/bash
set -eux

sudo taskset 0x30 \
output/host/bin/qemu-system-aarch64 \
	-append "console=ttyAMA0" \
	-cpu host \
	-device virtio-net-device,netdev=net0 \
	-enable-kvm \
	-initrd output/images/rootfs.cpio \
	-kernel output/images/Image \
	-machine virt \
	-netdev user,id=net0 \
	-nographic
