#!/bin/sh
#
# Custom.
#

NAME="custom"

start()
{
	printf 'Starting %s: ' "${NAME}"
	modprobe ledtrig-heartbeat
	echo usb-gadget >'/sys/class/leds/beaglebone:green:usr2/trigger'

	# If we run from eMMC, export SD card through USB.
	r=$(rdev |sed 's/ .*//')

	if [ "$r" = /dev/mmcblk1p2 ]; then
		modprobe g_mass_storage file=/dev/mmcblk0
	fi

	echo "OK"
}

stop()
{
	printf 'Stopping %s: ' "${NAME}"
	modprobe -r g_mass_storage
	echo cpu0 >'/sys/class/leds/beaglebone:green:usr2/trigger'
	modprobe -r ledtrig-heartbeat
	echo "OK"
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart|reload)
	stop
	start
	;;
*)
	echo "Usage: $0 {start|stop|restart|reload}" >&2
	exit 1
	;;
esac
