#!/bin/sh
#
# Custom.
#

NAME="custom"

start()
{
	printf 'Starting %s: ' "${NAME}"
	modprobe ledtrig-heartbeat
	echo usb-gadget >'/sys/class/leds/beaglebone:green:usr2/trigger'
	echo usb-host >'/sys/class/leds/beaglebone:green:usr3/trigger'
	r=$(rdev |sed 's/ .*//')

	if [ -e /dev/sda ]; then
		# If we have a USB key export it through USB.
		modprobe g_mass_storage file=/dev/sda

	elif [ -e /dev/mmcblk0 ] && [ "$r" = /dev/mmcblk1p2 ]; then
		# Otherwise, if we have an SD card and we run from eMMC, export
		# the SD card through USB.
		modprobe g_mass_storage file=/dev/mmcblk0
	fi

	mount / -o remount,ro
	echo "OK"
}

stop()
{
	printf 'Stopping %s: ' "${NAME}"
	mount / -o remount,rw
	modprobe -r g_mass_storage
	echo cpu0 >'/sys/class/leds/beaglebone:green:usr2/trigger'
	modprobe -r ledtrig-heartbeat
	echo "OK"
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart|reload)
	stop
	start
	;;
*)
	echo "Usage: $0 {start|stop|restart|reload}" >&2
	exit 1
	;;
esac
