#!/bin/sh
#
# Remount rootfs read-only.
#

NAME="ro"

start()
{
	printf 'Starting %s: ' "${NAME}"
	mount / -o remount,ro
	echo "OK"
}

stop()
{
	printf 'Stopping %s: ' "${NAME}"
	mount / -o remount,rw
	echo "OK"
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart|reload)
	stop
	start
	;;
*)
	echo "Usage: $0 {start|stop|restart|reload}" >&2
	exit 1
	;;
esac
