#!/bin/sh

case "$1" in
	start)
		echo "Starting custom"
		echo performance >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
		;;
	stop)
		echo "Stopping custom"
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac
